### PR TITLE
added code of conduct

### PR DESCRIPTION
**Pull request by javorszky**
For now I wholesale copied the one from the jsoxford site (https://github.com/jsoxford/website/blob/master/src/pages/codeofconduct.html), but the content will most definitely need to be tweaked somewhat.

### CODE REVIEW

**Review by omgmog — COMMENTED** [review]
Does this need to be html if it's a markdown file?

**Comment by javorszky** [comment]
Most probably not. It was the lowest effort copy paste on my part. Lemme remove the html bits

**Comment by javorszky** [comment]
Unnecessary html tags removed. 11ty also has this cool feature of automatically adding anchor links next to headers

**Comment by javorszky** [comment]
You can look at what this will look like by clicking this link too!

Netlify is awesome!

Markup on 2021-02-10 at 12:41:14

**Review by omgmog — APPROVED** [review]

**Pull request merged**
